server:
  port: 80
  
spring:
  application:
   name: microcloud-consumer  
  
eureka:
  client:
    register-with-eureka: true
    service-url:
        defaultZone: http://admin:fis@eureka1:7001/eureka,http://admin:fis@eureka2:7002/eureka,http://admin:fis@eureka3:7003/eureka
  instance:
    instance-id: microcloud-consumer
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5  # 如果现在超过了5秒的间隔（默认是90秒）      
    
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: # 可以被压缩的类型
       - text/xml
       - application/xml
       - application/json
      min-request-size: 2048 # 超过2048的字节进行压缩   
      
logging:
 level:
  com.fis.microcloud.service: DEBUG      