server:
  port: 8601
spring:
  application:
    name: microcloud-zipkin-server
  

management:
  metrics:
    web:
      server:
        auto-time-requests: false

zipkin:
  collector:
    sample-rate: 1.0
    http:
      enabled: false
    rabbitmq:
      addresses: fis-xiaolu-01:5672
      password: admin
      queue: zipkin
      username: admin
      virtual-host: /
  storage:
    type: mysql
    mysql:
      host: fis-xiaolu-03
      port: 3306
      username: root
      password: 123456
      db: zipkin