server:
  port: 8080
mybatis:
    # 所有的mapper映射文件
  mapper-locations: classpath:mapping/*.xml
spring:
  application:
   name: microcloud-provider-product
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 配置当前要使用的数据源的操作类型
    driverClassName: com.mysql.cj.jdbc.Driver # 配置MySQL的驱动程序类
    url: jdbc:mysql://fis-xiaolu-03:3306/springcloud?serverTimezone=GMT%2B8 # 数据库连接地址
    username: root # 数据库用户名
    password: 123456 # 数据库连接密码
#  security:
#    user:
#      name: root  # 认证用户名
#      password: root  # 认证密码
#      roles:
#      - USER # 授权角色  
      
logging:
  level: 
    com.fis.microcloud.provider.product: debug

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      #defaultZone: http://admin:fis@localhost:7001/eureka
      defaultZone: http://admin:fis@eureka1:7001/eureka,http://admin:fis@eureka2:7002/eureka,http://admin:fis@eureka3:7003/eureka
  instance:
    instance-id: microcloud-provider-product
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5  # 如果现在超过了5秒的间隔（默认是90秒）
    
    
info:
  app.name: microcloud-provider-product
  company.name: fis
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$    