server:
  port: 7201
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yxzyh/microconfig.git
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: fis-xiaolu-01
    port: 5672    # RabbitMQ的监听端口
    username: admin  # 用户名
    password: admin # 密码
  application:
    name: microcloud-config-bus

eureka:
 client:
  serviceUrl:
    defaultZone: http://admin:fis@localhost:7301/eureka
 instance:
    prefer-ip-address: true # 在地址栏上使用IP地址进行显示
    instance-id: microcloud-config-bus
management:
  endpoints:
    web:
      exposure:
        include: "*"