server:
  port: 80
  
  
eureka:
  client:
    register-with-eureka: false
    service-url:
        defaultZone: http://admin:fis@eureka1:7001/eureka,http://admin:fis@eureka2:7002/eureka,http://admin:fis@eureka3:7003/eureka